apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: apic-graphql
  annotations:
    description: Template to build a graphql container image to test applications on OCP.
    tags: apic,graphql
labels:
  template: apic-graphql
objects:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    name: apic-graphql
    namespace: ${APP_NAMESPACE}
  spec:
    replicas: 3
    revisionHistoryLimit: 1
    selector:
      app: apic-graphql
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        name: apic-graphql
        labels:
          app: apic-graphql
      spec:
        containers:
          -
            # args:
            #   - while true; do sleep 30; done;
            # command:
            #   - /bin/sh
            #   - '-c'
            #   - '--'
            name: apic-graphql
            image: ""
            imagePullPolicy: Always
            # ports:
            #   - name: http
            #     containerPort: 8080
            #     protocol: TCP
            volumeMounts:
            - mountPath: /etc/cred
              name: apis-minim-780c5c89-780c5c89-postgres-postgres-secret
              readOnly: true
            - mountPath: /etc/cert
              name: apis-minim-780c5c89-db-client-postgres
              readOnly: true
        # volumes:
        #   - name: app-config
        #     configMap:
        #       name: apic-graphql-config
        volumes:
        - name: apis-minim-780c5c89-780c5c89-postgres-postgres-secret
          secret:
            defaultMode: 420
            secretName: apis-minim-780c5c89-780c5c89-postgres-postgres-secret
        - name: apis-minim-780c5c89-780c5c89-postgres-postgres-secret-apicuser
          secret:
            defaultMode: 420
            secretName: apis-minim-780c5c89-780c5c89-postgres-postgres-secret-apicuser
        - name: apis-minim-780c5c89-ca
          secret:
            defaultMode: 420
            secretName: apis-minim-780c5c89-ca
        - name: apis-minim-780c5c89-client
          secret:
            defaultMode: 420
            secretName: apis-minim-780c5c89-client
        - name: apis-minim-780c5c89-db-client-apicuser
          secret:
            defaultMode: 420
            secretName: apis-minim-780c5c89-db-client-apicuser
        - name: apis-minim-780c5c89-db-client-postgres
          secret:
            defaultMode: 420
            secretName: apis-minim-780c5c89-db-client-postgres
        - name: apis-minim-780c5c89-server
          secret:
            defaultMode: 420
            secretName: apis-minim-780c5c89-server
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - apic-graphql
        from:
          kind: ImageStreamTag
          name: apic-graphql:v1
parameters:
  - name: APP_NAMESPACE
    description: "The namespace of the application."
    required: true
